site_name: Foldable Robotics Camp
repo_url: https://github.com/idealabasu/foldable-camp
edit_uri: edit/main/docs/
theme:
  name: material
  custom_dir: custom_theme/
  palette:
    primary: blue
    accent: indigo
  font:
    text: Roboto
  logo: logo.svg
  favicon: logo.png

  features:
#    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
#    - navigation.sections
#    - navigation.expand
    - toc.follow    
#    - toc.integrate 
    - navigation.top
    - navigation.path
    - navigation.indexes
    - navigation.prune
    - content.action.edit

markdown_extensions:
  - pymdownx.tilde: {}


draft_docs: |
  **/*_unpublished.md
  **/*_draft.md




# nav:
# - index.md
# - what-to-bring.md
# - daily-schedule.md
# - lesson-plan.md
# - instructor-information.md
# - classroom-info.md
# - presentations
#   - biomechanics-and-bioinspiration
#   - foldable-mechanisms